CREATE TRIGGER TRIGGER_ONE_123141
ON HBSERVER.DBO.result_lugdown AFTER
INSERT
AS
UPDATE HBSERVER.DBO.result_lugdown SET K80='0' FROM INSERTED,HBSERVER.DBO.result_lugdown WHERE HBSERVER.DBO.result_lugdown.FID=INSERTED.FID
GO

